
sudo: true
language: cpp
compiler:
- gcc
os:
- linux
install:
- CURRENT=`pwd`
- sudo apt-get install libgtest-dev
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- cd $CURRENT
script:
- cmake .
- make all
- cd test && ctest .

