
sudo: true
language: cpp
compiler:
- gcc
os:
- linux
before_install:
- sudo apt-get install libgtest-dev
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
script:
- cmake .
- make all
- cd test && ctest .

